### PR TITLE
Develop branch for julia1.0

### PR DESCRIPTION
**Pull request by leejm516**
I confirmed that this branch passed the test with `saveDistributedFBA` being inactivated. I have been still struggling with the issue of `saveDistributedFBA`, but I have no idea to access variables outside the function using `eval()`.

### CODE REVIEW

**Comment by leejm516** [comment]
I am very scared of touching anything in this repository. If I have done something wrong, please let me know :)

**Comment by leejm516** [comment]
There is no problem in the package test (by executing `]test COBRA`) with Clp and GLPK solvers while testing with CPLEX throws `ERROR: LoadError: LoadError: IOError: unlink: resource busy or locked (EBUSY)` in `p_all.jl`.

**Comment by laurentheirendt** [comment]
Thanks @leejm516. I am currently working on getting the CI up-to-speed with Julia 1.0+.

**Comment by leejm516** [comment]
@laurentheirendt, this commit makes us use `saveDistributedFBA` in Julia >= 1.0 while keeping the arguments of the functions. I overthought this problem -_-;

**Comment by laurentheirendt** [comment]
@leejm516, may you rebase your branch here? Thanks. 👍

**Comment by leejm516** [comment]
I am not sure if I did rebase properly. Please let me know if something is wrong. The last commit passed the test.

**Comment by laurentheirendt** [comment]
@leejm516, no the rebase went wrong here, unfortunately.

**Comment by leejm516** [comment]
@laurentheirendt Oops... I thought you wanted me to rebase my PR to the current develop branch (since you have merged another PR). Could you explain "rebase" in more detail? Do you want to make this PR exist as a seperate branch?

**Comment by laurentheirendt** [comment]
What commands did you run?

**Comment by leejm516** [comment]
To apply the recent changes in my fork repository, I ran the following commands.
```
$ git remote add upstream https://github.com/opencobra/COBRA.jl.git
$ git fetch upstream
$ git checkout develop
$ git merge upstream/develop
```

Then I performed rebase.
```
git checkout develop-julia1.0
git rebase develop
```

Should I revert the branch?

**Comment by laurentheirendt** [comment]
@leejm516, you basically rebased after merging. As you did a fast-forward merge, you have no other option but cherry-picking your commits on a new branch from the current `develop` branch.

**Comment by leejm516** [comment]
That is not a big deal. I will do it with the current branch this week. Thanks

**Comment by laurentheirendt** [comment]
@leejm516, may we finish this PR? 👍

**Comment by leejm516** [comment]
@laurentheirendt, I am sorry for that. I was busy last week finishing a manuscript. I will do it this week.

**Comment by laurentheirendt** [comment]
Sounds good 👍 Looking forward to that.

**Pull request closed without merging**
